name: the_link_up
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #plugins
  cupertino_icons: ^0.1.2
  dots_indicator: ^1.0.0
  provider: ^3.0.0+1
  toast: ^0.1.5
  http: ^0.12.0+4
  flutter_secure_storage: ^3.3.1+1
  dio: ^3.0.8
  fancy_alert_dialog: ^0.0.1
  font_awesome_flutter: ^8.5.0
  datetime_picker_formfield: ^1.0.0
  getflutter: ^1.0.5
  splashscreen: ^1.2.0
  flutter_svg: ^0.17.1
  cached_network_image: 2.0.0-rc
  http_parser: ^3.1.3
  image_cropper: ^1.2.1
  image_picker: ^0.6.2+3 # needed to configure for iso
  #chat
  web_socket_channel: ^1.0.12
  geolocator: ^5.2.1
  flutter_spinkit: ^4.1.1+1
  app_settings: ^3.0.0+1
  location: ^2.4.0
  #fcm
  firebase_messaging: ^6.0.12


dev_dependencies:
  flutter_launcher_icons: ^0.7.4

  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0
  #app_settings: 3.0.0+1

#logo icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logo/splash.png
    - images/logo/logo.png
  fonts:
    - family: ReemKufi
      fonts:
        - asset: fonts/ReemKufi-Regular.ttf

    - family: Poppins Light
      fonts:
        - asset: fonts/Poppins-Light.ttf

    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Poppins SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf